#!/usr/bin/env node
'use strict';

// Every message in this file was written for this file. The detector's real
// accuracy is measured against a labelled set of the user's own messages, which
// stays on their machine and out of this public repository, and is run with
// `pushback.js --selftest`. What is tested here is the mechanics: what counts as
// the user talking, what counts as pasted content, and that each kind of
// pushback is reachable. A green run here does not mean the detector is
// accurate. It means it is wired up.

const assert = require('assert');
const fs = require('fs');
const os = require('os');
const path = require('path');

const P = require('../plugins/build-loop/scripts/pushback.js');

let failed = 0;
let total = 0;
function check(label, fn) {
  total += 1;
  try {
    fn();
    console.log(`  ok    ${label}`);
  } catch (error) {
    failed += 1;
    console.log(`  FAIL  ${label}\n        ${error.message}`);
  }
}

// --- what counts as the user talking ---------------------------------------

const user = (content, extra) => Object.assign({ type: 'user', userType: 'external', message: { role: 'user', content } }, extra || {});

check('a plain typed message is the user talking', () => {
  assert.strictEqual(P.userText(user('i dont understand')), 'i dont understand');
});

check('a text block array is the user talking', () => {
  assert.strictEqual(P.userText(user([{ type: 'text', text: 'huh?' }])), 'huh?');
});

check('a tool result is not the user talking', () => {
  assert.strictEqual(P.userText(user([{ type: 'tool_result', content: 'i dont understand' }])), null);
});

check('a tool result carrying a text block alongside it is still not the user talking', () => {
  // The bare tool_result case passes even with the guard removed, because an
  // array with no text block yields nothing anyway. This is the shape that
  // actually exercises the guard: a real tool result record often carries both,
  // and without the guard its text is counted as something the user typed.
  assert.strictEqual(
    P.userText(user([{ type: 'tool_result', content: 'x' }, { type: 'text', text: 'i dont understand' }])),
    null
  );
});

check('a sidechain turn is not the user talking', () => {
  assert.strictEqual(P.userText(user('what?', { isSidechain: true })), null);
});

check('an assistant record is not the user talking', () => {
  assert.strictEqual(P.userText({ type: 'assistant', message: { content: 'what?' } }), null);
});

check('every injected wrapper is excluded', () => {
  // Each of these arrives as role "user" and none is the user typing. Missing
  // one inflates the denominator and quietly deflates the rate, which is the
  // one number this whole script exists to produce.
  const wrappers = [
    '<command-message>session:wrap</command-message>',
    '<command-name>/wrap</command-name>',
    '<local-command-stdout>done</local-command-stdout>',
    '<local-command-caveat>Caveat: ...</local-command-caveat>',
    '<bash-input> git status</bash-input>',
    '<bash-stdout>clean</bash-stdout>',
    '<system-reminder>note</system-reminder>',
    '[Request interrupted by user]',
    'Caveat: The messages below were generated by the user',
    'Stop hook feedback: Style violation in the response',
    'Base directory for this skill: /some/path',
  ];
  for (const w of wrappers) {
    assert.strictEqual(P.userText(user(w)), null, `not excluded: ${w.slice(0, 40)}`);
  }
});

check('an empty or whitespace message is not counted', () => {
  assert.strictEqual(P.userText(user('   \n  ')), null);
});

// --- each kind of pushback is reachable ------------------------------------

check('every kind has at least one message that reaches it', () => {
  const samples = {
    'off-track': 'stop going off track, fix the pull request before we do anything else',
    distrust: 'are you sure you ran all of those tests',
    'cannot-understand': 'too much jargon i dont understand any of this',
    'no-next-action': 'ok great now what',
    undecidable: 'this doesnt help me make a decision',
    'what-is-this': 'how is the first one different from the second one',
  };
  for (const k of P.KINDS) {
    assert.ok(samples[k.kind], `no sample written for kind ${k.kind}`);
    assert.strictEqual(P.classify(samples[k.kind]), k.kind, `${k.kind} not reached`);
  }
});

check('ordinary working messages are not pushback', () => {
  const calm = [
    'yes do it', 'merge it', 'push it and open the PR', 'y', 'clean from devin merge it',
    'yes, start with the probe test', 'add the three', 'lets wrap', 'do 1 and 3',
    'can you move those files', 'fix the memory note', 'ok looks good', 'great',
  ];
  for (const c of calm) {
    assert.strictEqual(P.classify(c), null, `wrongly flagged: ${c}`);
  }
});

check('a message that only reports someone else being confused is not pushback', () => {
  // Real case that used to trip the bare word. She was editing a post and said a
  // term would confuse its readers, which is not her pushing back on an answer.
  const s = 'I dont want to use the word funnel in here. I think its confusing so lets stick with landing pages.';
  assert.strictEqual(P.classify(s), null);
});

// --- pasted content is not the user being confused -------------------------

check('a forwarded review finding is not pushback', () => {
  const s = '1 bug plugins/session/scripts/handoffs.js:343 **A handoff being written can still be dropped** '
    + 'The index note is confusing and i dont understand why it does that.';
  assert.strictEqual(P.classify(s), null);
});

check('a forwarded finding is caught by its markup even without a leading marker', () => {
  // The case above opens with "1 bug", so the leading-marker guard catches it
  // and the markup guard is never reached. This one opens with ordinary words,
  // the way a forwarded flag usually does, so only the markup guard can stop it.
  const s = 'still this 1 flag, do we care? i dont understand it. '
    + 'plugins/slop-check/hooks/style-lint.js:103 **Prose written before a tool call is never linted**';
  assert.strictEqual(P.classify(s), null);
});

check('a pasted terminal block is not pushback', () => {
  assert.strictEqual(P.classify('• UserPromptSubmit hook (failed) what does this mean'), null);
});

check('a very long message is not counted as pushback', () => {
  const s = 'i dont understand. ' + 'x'.repeat(900);
  assert.strictEqual(P.classify(s), null);
});

check('a short message just under the ceiling is still counted', () => {
  const s = 'i dont understand any of this. ' + 'x'.repeat(700);
  assert.ok(s.length < 800);
  assert.strictEqual(P.classify(s), 'cannot-understand');
});

// --- scanning a transcript tree --------------------------------------------

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'pushback-test-'));
const nested = path.join(tmp, 'a-project');
fs.mkdirSync(nested);

function line(o) { return JSON.stringify(o) + '\n'; }

const when = '2026-08-16T12:00:00.000Z';
fs.writeFileSync(path.join(nested, 's.jsonl'),
  line({ type: 'assistant', timestamp: when, message: { content: [{ type: 'text', text: 'a'.repeat(500) + ' worth flagging that my first pass was wrong' }] } })
  + line(Object.assign({ timestamp: when }, user('too much jargon i dont understand')))
  + line(Object.assign({ timestamp: when }, user('yes do it')))
  + line(Object.assign({ timestamp: when }, user('<bash-input> ls</bash-input>')))
  + line(Object.assign({ timestamp: when }, user([{ type: 'tool_result', content: 'x' }]))));

check('scan finds transcripts in nested directories', () => {
  const r = P.scan(0, tmp);
  assert.strictEqual(r.files, 1);
});

check('scan counts only what the user typed', () => {
  const r = P.scan(0, tmp);
  assert.strictEqual(r.typed.length, 2, `counted ${r.typed.length}`);
});

check('scan finds the pushback and attaches the answer before it', () => {
  const r = P.scan(0, tmp);
  assert.strictEqual(r.pushbacks.length, 1);
  assert.strictEqual(r.pushbacks[0].kind, 'cannot-understand');
  assert.ok(r.pushbacks[0].answer, 'no preceding answer attached');
  assert.match(r.pushbacks[0].answer.text, /worth flagging/);
});

check('the window cutoff excludes older messages', () => {
  const future = new Date('2026-08-17T00:00:00Z').getTime();
  const r = P.scan(future, tmp);
  assert.strictEqual(r.typed.length, 0);
});

check('the rate is per hundred typed messages', () => {
  assert.strictEqual(P.rate(1, 2), 50);
  assert.strictEqual(P.rate(0, 0), 0, 'an empty window must not divide by zero');
});

check('the signal check reads the tail for a handover, not the whole answer', () => {
  const s = P.signals([{ answer: { text: 'x'.repeat(600) + ' and my first pass was wrong' } }]);
  assert.strictEqual(s.counted, 1);
  assert.strictEqual(s.narrates, 1);
  assert.strictEqual(s.noHandover, 1, 'an answer ending on its own process hands over nothing');
});

// --- the report keeps the user's words off any external surface ------------

check('quoting is off unless it is asked for, in every shape of not asking', () => {
  // The defect this replaces: quoting was the default and one string comparison
  // against "slack" was the only thing keeping private messages out of a channel.
  // Three spellings got past it. The control now fails closed, so the test is
  // that every way of not asking produces counts.
  const r = P.scan(0, tmp);
  const waysOfNotAsking = [
    {},
    { quotes: false },
    { quotes: 'yes' },
    { quotes: 1 },
    { format: 'local' },
    { format: 'slack' },
    { quote: true },
    undefined,
  ];
  for (const opts of waysOfNotAsking) {
    const out = P.report(r, opts);
    assert.ok(out.includes('Pushback rate'), `no rate for ${JSON.stringify(opts)}`);
    assert.ok(!out.includes('too much jargon'),
      `quoted the user for ${JSON.stringify(opts)}, which must never happen without quotes: true`);
  }
});

check('quoting happens when it is asked for, so the local report is still useful', () => {
  const r = P.scan(0, tmp);
  const out = P.report(r, { quotes: true });
  assert.ok(out.includes('too much jargon'),
    'with quotes: true the report should quote, so a pattern can be acted on');
});

// --- argument parsing refuses what it does not understand ------------------

check('a valid command line parses to the values it names', () => {
  const a = P.parseArgs(['--days', '14', '--quotes', '--json']);
  assert.strictEqual(a.days, 14);
  assert.strictEqual(a.quotes, true);
  assert.strictEqual(a.json, true);
});

check('the defaults are the safe ones', () => {
  const a = P.parseArgs([]);
  assert.strictEqual(a.quotes, false, 'quoting must be off by default');
  assert.strictEqual(a.days, 7);
  assert.strictEqual(a.json, false);
});

check('every shape that used to leak quotes is now a hard error', () => {
  // Each of these produced the full quoting report before, while looking like
  // the safe command. None of them may be silently accepted again.
  const leaks = [
    ['--format=slack'],
    ['--format', 'Slack'],
    ['--format', 'slack'],
    ['--format'],
    ['--quiet'],
    ['--quotes=false'],
  ];
  for (const argv of leaks) {
    assert.throws(() => P.parseArgs(argv), /unknown argument|takes no value|takes its value/,
      `silently accepted ${JSON.stringify(argv)}`);
  }
});

check('a days value that is not a positive number is refused', () => {
  for (const bad of ['seven', '0', '-3', 'NaN', 'Infinity', '']) {
    assert.throws(() => P.parseArgs(['--days', bad]),
      /needs a positive number|needs a value/,
      `accepted --days ${JSON.stringify(bad)}, which would report every conversation ever recorded`);
  }
});

check('a flag given as another flag value is refused rather than swallowed', () => {
  assert.throws(() => P.parseArgs(['--days', '--json']), /needs a value/);
  assert.throws(() => P.parseArgs(['--days']), /needs a value/);
  assert.throws(() => P.parseArgs(['--root']), /needs a value/);
});

check('an unrecognised flag is refused even in the value position', () => {
  // A known flag in the value position is caught by the flag table. An unknown
  // one is not, so without the leading-dashes check `--root --bogus` would take
  // "--bogus" as a directory path and scan nothing, reporting a clean zero.
  assert.throws(() => P.parseArgs(['--root', '--bogus']), /needs a value/);
  assert.throws(() => P.parseArgs(['--fixture', '--bogus']), /needs a value/);
});

check('a report over an empty window says so rather than dividing by zero', () => {
  const out = P.report({ typed: [], pushbacks: [], byKind: {}, files: 0 }, {});
  assert.match(out, /nothing to report/);
});

check('the report states that the number is a floor', () => {
  const r = P.scan(0, tmp);
  assert.match(P.report(r, {}), /floor/);
});

// --- selftest is honest when it has nothing to measure against -------------

check('selftest reports that nothing was measured when the labelled set is absent', () => {
  const r = P.selftest(path.join(tmp, 'does-not-exist.json'));
  assert.strictEqual(r.ok, false);
  assert.match(r.reason, /Nothing was measured/);
});

check('selftest counts catches and false positives against a labelled set', () => {
  const f = path.join(tmp, 'fixture.json');
  fs.writeFileSync(f, JSON.stringify([
    { text: 'i dont understand', pushback: true },
    { text: 'ok great now what', pushback: true },
    { text: 'yes do it', pushback: false },
    { text: 'merge it', pushback: false },
  ]));
  const r = P.selftest(f);
  assert.strictEqual(r.ok, true);
  assert.strictEqual(r.positives, 2);
  assert.strictEqual(r.caught, 2);
  assert.strictEqual(r.wrong.length, 0);
  assert.strictEqual(r.catchPct, 100);
});

fs.rmSync(tmp, { recursive: true, force: true });

console.log(`\n${total} checks, ${failed} failed`);
process.exit(failed === 0 ? 0 : 1);
