#!/usr/bin/env node
// Wire the status line up, without pinning settings.json to a version that
// will not exist next week.
//
// ---------------------------------------------------------------------------
// The problem this solves, which is not obvious until it bites.
//
// A plugin cannot ship a status line. Claude Code reads `statusLine` from
// settings.json and from nowhere else; the plugin component inventory is
// skills, agents, hooks, MCP servers and LSP servers, and that is the whole
// list. So the file can live in the plugin, but something in settings.json has
// to point at it.
//
// The tempting one line is to point straight at the installed copy:
//
//   ~/.claude/plugins/cache/smadds/session/0.1.0/statusline/statusline.js
//
// That path contains the version. Updating the plugin creates a new directory
// beside it and leaves the old one in place, so the setting keeps resolving,
// keeps rendering, and keeps rendering the version you stopped using. Nothing
// errors. The only symptom is a fix you shipped that never appears.
//
// This is not hypothetical. It is the `live-path-stale` finding from the
// ip-inventory audit, which exists because fs.existsSync passing is not the
// same as a path being live, and a superseded version directory passes.
//
// So settings.json points at one fixed path instead, and the file there
// resolves the newest installed version at render time. Written once, correct
// after every update, nothing to remember.

'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');

const SHIM_PATH = (home = os.homedir()) => path.join(home, '.claude', 'statusline.js');

// Newest-first by version. Plain numeric comparison per segment, because the
// versions here are the plugin's own and are always three numbers.
function compareVersions(a, b) {
  const pa = String(a).split('.').map((n) => parseInt(n, 10) || 0);
  const pb = String(b).split('.').map((n) => parseInt(n, 10) || 0);
  for (let i = 0; i < Math.max(pa.length, pb.length); i += 1) {
    const d = (pb[i] || 0) - (pa[i] || 0);
    if (d) return d;
  }
  return 0;
}

// Every installed copy of this plugin's status line, newest first.
//
// Scans across marketplaces rather than assuming `smadds`, so this still works
// for anyone who added the marketplace under a different name.
function installedStatuslines(home = os.homedir()) {
  const cache = path.join(home, '.claude', 'plugins', 'cache');
  const found = [];

  let marketplaces;
  try { marketplaces = fs.readdirSync(cache); } catch (_) { return found; }

  for (const market of marketplaces) {
    const pluginDir = path.join(cache, market, 'session');
    let versions;
    try { versions = fs.readdirSync(pluginDir); } catch (_) { continue; }
    for (const version of versions) {
      const file = path.join(pluginDir, version, 'statusline', 'statusline.js');
      try {
        if (fs.statSync(file).isFile()) found.push({ market, version, path: file });
      } catch (_) { /* not this one */ }
    }
  }

  return found.sort((a, b) => compareVersions(a.version, b.version));
}

// The file settings.json points at. Deliberately tiny and deliberately silent
// on failure: a status line that throws takes the prompt with it, and a missing
// segment is a far better outcome than a broken shell.
function shimSource() {
  return `#!/usr/bin/env node
// Generated by the 'session' plugin. Safe to overwrite.
//
// settings.json points here rather than at the plugin's install directory,
// because that directory has a version number in it and updating the plugin
// would leave this setting quietly rendering the previous release.
//
// This resolves the newest installed copy on every render instead.
'use strict';
const fs = require('fs');
const os = require('os');
const path = require('path');

function newest() {
  const cache = path.join(os.homedir(), '.claude', 'plugins', 'cache');
  let best = null;
  let bestV = null;
  let markets = [];
  try { markets = fs.readdirSync(cache); } catch (e) { return null; }
  for (const m of markets) {
    let versions = [];
    try { versions = fs.readdirSync(path.join(cache, m, 'session')); } catch (e) { continue; }
    for (const v of versions) {
      const file = path.join(cache, m, 'session', v, 'statusline', 'statusline.js');
      try { if (!fs.statSync(file).isFile()) continue; } catch (e) { continue; }
      const parts = v.split('.').map(function (n) { return parseInt(n, 10) || 0; });
      if (!bestV || compare(parts, bestV) > 0) { best = file; bestV = parts; }
    }
  }
  return best;
}

function compare(a, b) {
  for (let i = 0; i < Math.max(a.length, b.length); i++) {
    const d = (a[i] || 0) - (b[i] || 0);
    if (d) return d;
  }
  return 0;
}

let input = '';
const timer = setTimeout(function () { process.exit(0); }, 3000);
process.stdin.setEncoding('utf8');
process.stdin.on('data', function (c) { input += c; });
process.stdin.on('error', function () { process.exit(0); });
process.stdin.on('end', function () {
  clearTimeout(timer);
  try {
    const target = newest();
    if (target) {
      process.stdout.write(require(target).renderStatusline(JSON.parse(input)));
    } else {
      // Deliberately not silence.
      //
      // settings.json points here, so somebody switched the status line on. If
      // this cannot find the plugin, rendering nothing produces a blank line
      // that looks exactly like a status line that was never configured, and
      // there is no way to tell those apart by looking. That is the precise
      // failure this whole plugin was written to stop repeating.
      //
      // Saying so costs one dim line and names the fix.
      process.stdout.write('\\x1b[2msession plugin not found, run /status-bar\\x1b[0m');
    }
  } catch (e) {
    // A thrown error is different: it is a bug here, not a missing install,
    // and the prompt must survive it.
  }
  process.exit(0);
});
`;
}

// The exact settings.json fragment to add. Returned rather than written.
//
// Nothing here edits settings.json. That file holds permissions and enabled
// plugins, a plugin rewriting it unasked is the kind of thing that should be
// refused rather than automated, and the skill shows this and waits.
// The interpreter is named absolutely, resolved now rather than looked up later.
//
// This used to emit `node "<shim>"`, which is the same defect the hooks had
// until 2026-08-13: an app launched from the Dock never reads a shell profile,
// so it gets a bare PATH, and on a machine where node was not installed
// system-wide the status line dies with 127. A status line that fails is even
// quieter than a hook that fails, because there is nothing there to notice.
//
// bin/hook-node is deliberately not used here, though it solves the same
// problem for hooks. It lives inside the installed plugin, whose path carries a
// version number and is replaced on the next update, and this string is written
// into the user's settings.json where it has to keep working afterwards.
// tests/session-handoffs.test.js asserts the fragment never points into
// plugins/cache for that reason.
//
// process.execPath is the node currently running this installer, so it needs no
// candidate list and cannot disagree with one. Re-running the installer
// refreshes it if node ever moves.
function settingsFragment(home = os.homedir()) {
  return {
    statusLine: {
      type: 'command',
      command: `"${process.execPath}" "${SHIM_PATH(home)}"`,
    },
  };
}

function install({ home = os.homedir(), dryRun = false } = {}) {
  const target = SHIM_PATH(home);
  const source = shimSource();
  const installed = installedStatuslines(home);

  let existing = null;
  try { existing = fs.readFileSync(target, 'utf8'); } catch (_) { /* not there yet */ }

  const unchanged = existing === source;
  if (!dryRun && !unchanged) {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, source, { mode: 0o755 });
  }

  return {
    shimPath: target,
    wrote: !dryRun && !unchanged,
    unchanged,
    // Empty on a first install from a working copy, since nothing is in the
    // plugin cache until the marketplace install runs. Reported rather than
    // treated as an error, because the shim resolves at render time and will
    // start working the moment a copy appears.
    installedVersions: installed.map((i) => `${i.market}/${i.version}`),
    settingsFragment: settingsFragment(home),
  };
}

if (require.main === module) {
  const dryRun = process.argv.includes('--dry-run');
  process.stdout.write(`${JSON.stringify(install({ dryRun }), null, 2)}\n`);
}

module.exports = {
  SHIM_PATH, compareVersions, installedStatuslines, shimSource, settingsFragment, install,
};
